[[project]]
name = "X++"
desc = "An interpreter for a functional programming language developed as part of the Programming Languages course"
tags = ["Programming Languages", "Interpreter"]
links = [
  { name = "GitHub Repository", url = "https://github.com/joserlopes/Programming-Languages" },
]
